config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'home#index'

  resources :artists
  resources :museums
  resources :paintings

end

app/models/artist.rb
class Artist < ActiveRecord::Base
  has_many :paintings
end

app/models/museum.rb
class Museum < ActiveRecord::Base
  has_many :paintings
  has_many :artists, through: :paintings
end

app/models/painting.rb
class Painting < ActiveRecord::Base
  belongs_to :artist
  belongs_to :museum

  def self.search(input)
    self.where("title LIKE :input or year LIKE :input or style LIKE :input", input: "%#{input}%")
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!, :except => [:index, :show]
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  def index
    @search = params[:search]
    @artists = @search ? Artist.search(@search) : @artists = Artist.all
  end

  def new
    @artist = Artist.new
  end

  def create
    @artist = Artist.new(artist_params)

    if @artist.save
      redirect_to artists_path
    else
      render 'new'
    end
  end

  def show
  end

  def edit
    @artist = Artist.find(params[:id])
  end

  def update
    @artist = Artist.find(params[:id])

    if @artist.update(artist_params)
      redirect_to artists_path
    else
      render 'edit'
    end
  end

  def destroy
    artist.find(params[:id]).delete
    redirect_to artists_path
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/museums_controller.rb
class MuseumsController < ApplicationController
  def index
    @search = params[:search]
    @museums = @search ? Museum.search(@search) : @museums = Museum.all
  end

  def new
    @museum = Museum.new
  end

  def create
    @museum = Museum.new(museum_params)

    if @museum.save
      redirect_to museums_path
    else
      render 'new'
    end
  end

  def show
    @museum = Museum.find(params[:id])
  end

  def edit
    @museum = Museum.find(params[:id])
  end

  def update
    @museum = Museum.find(params[:id])

    if @museum.update(museum_params)
      redirect_to museums_path
    else
      render 'edit'
    end
  end

  def destroy
    Museum.find(params[:id]).delete
    redirect_to museums_path
  end
end

app/controllers/paintings_controller.rb
class PaintingsController < ApplicationController
  def index
    @search = params[:search]
    @paintings = @search ? Painting.search(@search) : @paintings = Painting.all
  end

  def new
    @painting = Painting.new
  end

  def create
    @painting = Painting.new(painting_params)

    if @painting.save
      redirect_to paintings_path
    else
      render 'new'
    end
  end

  def show
    @painting = Painting.find(params[:id])
  end

  def edit
    @painting = Painting.find(params[:id])
  end

  def update
    @painting = Painting.find(params[:id])

    if @painting.update(painting_params)
      redirect_to paintings_path
    else
      render 'edit'
    end
  end

  def destroy
    Painting.find(params[:id]).delete
    redirect_to paintings_path
  end

  private

  def painting_params
    params.require(:painting).permit(:title, :year, :style)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/museums_helper.rb
module MuseumsHelper
end

app/helpers/paintings_helper.rb
module PaintingsHelper
end

app/views/home/index.html.erb
<h1>Welcome to MuseumApp</h1>

<%= link_to  "View Our Collection", paintings_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MuseumApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if user_signed_in? %>
  <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path %> | <%= link_to "Sign in", new_user_session_path %>
<% end %>

<%= yield %>

</body>
</html>

app/views/museums/_form.html.erb
<%= form_for @museum do |f| %>
  <br>
  <div>
  <%= f.label :name %>
  <%= f.text_field :name %>
  </div>
  <br>
  <div>
  <%= f.label :city %>
  <%= f.text_field :city %>
  <%= f.submit %>
<% end %>

app/views/paintings/_form.html.erb
<%= form_for @painting do |f| %>
  <br>
  <div>
  <%= f.label :title %>
  <%= f.text_field :title %>
  </div>
  <br>
  <div>
  <%= f.label :year %>
  <%= f.text_field :year %>
  </div>
  <br>
  <div>
  <%= f.label :style %>
  <%= f.text_field :style %>
  </div>
  <br>
  <div>
  <%= f.label :image %>
  <%= f.text_field :image %>
  </div>
  <br>
  <%= f.collection_select(:museum_id, Museum.all, :id, :name, { :prompt => 'Select a Museum', :selected => @painting.museum_id }, { class: 'form-control' }) %>
  <br>
  <%= f.collection_select(:artist_id, Artist.all, :id, :name, { :prompt => 'Select an Artist', :selected => @painting.artist_id }, { class: 'form-control' }) %>
  <%= f.submit %>
<% end %>

app/views/paintings/_search.html.erb
<%= form_tag paintings_path, method: 'get' do %>
  <%= text_field_tag 'search', @search %>
  <%= submit_tag 'Search' %>
<% end %>

app/views/paintings/edit.html.erb
<%= render 'form' %>
<br>
<%= link_to "Cancel", paintings_path %>

app/views/paintings/index.html.erb
<br>
<br>
<table>
  <tr>
    <th>Title</th>
    <th>Year</th>
    <th>Style</th>
  </tr>

<%= render 'search' %>
<br>
<br>
<% @paintings.each do |painting| %>
  <tr>
    <td><%= painting.title %></td>
    <td><%= painting.year %></td>
    <td><%= painting.style %></td>
    <td><%= link_to "Show", painting_path(painting) %></td>
    <td><%= link_to "Edit", edit_painting_path(painting) %></td>
    <td><%= link_to "Delete", painting, method: :delete, data: { confirm: "You sure?" } %></td>
  </tr>
<% end %>
</table>
<br>

<%= link_to "Add a painting to our collection", new_painting_path %>

app/views/paintings/new.html.erb
<%= render 'form' %>
<br>
<%= link_to "Cancel", paintings_path %>

app/views/paintings/show.html.erb
<h1><%= @painting.title %></h1>
<%= image_tag @painting.image %>

<p><%= @painting.year %></p>
<p><%= @painting.style %></p>
<p><%= @painting.artist.name %></p>
<p>Held at the <%= @painting.museum.name %> in <%= @painting.museum.city %></p>

<%= link_to "Back to full collection", paintings_path %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>